### ISSUE TITLE
Portaging BossRc500 under macos 12.1

### ISSUE THREAD

**Issue by tom1lee** [dfleury2/boss-rc500-editor#1]
Operating System+version: Mac Monterey 12.1
Compiler+version: Clang 13.0.0
Conan version: 1.44.0
Python version: 3.9.9
Command line tools/Xcode version: 13.2.1

I finally succeeded in building make under MacOs ... Thanks to the founder ! 👍 

In these three files:

~/jeanjean/boss-rc500-editor/sources/BossRc500/main.cpp
~/boss-rc500-editor/sources/BossRc500-MemoryCopy/main.cpp
~/boss-rc500-editor/sources/WidgetExamples/WidgetMain.cpp

Just delete these functions:

#ifdef LINUX

Q_IMPORT_PLUGIN(QXcbIntegrationPlugin)
#else
Q_IMPORT_PLUGIN(QWindowsIntegrationPlugin)
#endif

-----------------------------

Now, trying to open binary from the terminal :

Last login: Tue Jan  4 15:06:19 on ttys001
~/boss-rc500-editor/build/sources/BossRc500/BossRc500 ; exit;     
me@Mini-de-me ~ % ~/boss-rc500-editor/build/sources/BossRc500/BossRc500 ; exit;
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

zsh: abort      ~/boss-rc500-editor/build/sources/BossRc500/BossRc500

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Opération terminée]

------------------------------

I don't know anything about Qt creator, could it be enough to just install a plugin in Qt ?
I check that, and I come back ...
Any help will be welcome ! Thanks.

**Comment by dfleury2** [comment]
Hi, 
welcome here ;)

You have this issue because the Cocoa pluing is missing. 
One line like this one : 'Q_IMPORT_PLUGIN(QXcbIntegrationPlugin)'
Must be present in the main.

So MacOs, somewhere there should be a plugin for the abstraction layer somehting like 'QCocoaIntregrationPlugin'

You can try adding this line instead :

```
Q_IMPORT_PLUGIN(QCocoaIntegrationPlugin);
```

I can not test because I do not have a MacOS to experiment with but you can find a file with this name near ~/.conan/data/qt/6.2.1/_/_/package/<a long string there>/lib

You can find something like : libXCocoaIntegrationPlugin

**Comment by tom1lee** [comment]
Hi ! @dfleury2 ! Please to meet you here ! !)

Unfortunately, whether with, 'Q_IMPORT_PLUGIN(QXcbIntegrationPlugin);' or with 'Q_IMPORT_PLUGIN(QXcbIntegrationPlugin);' in the main ,make becomes impossible.

About libs...

Under ~/.conan/data/qt/6.2.1///package/... I find two dir like these below which each contain a lib dir.

~/.conan/data/qt/6.2.1///package/9c39a041ef08c69eb3a82026999134a5b7aecf3b/lib/ Contains : ...
libQt6FbSupport.prl			libQt6OpenGLWidgets.prl			libQt6Widgets.prl
libQt6Concurrent.a			libQt6Gui.a				libQt6PrintSupport.a			libQt6Xml.a
libQt6Concurrent.prl			libQt6Gui.prl				libQt6PrintSupport.prl			libQt6Xml.prl
libQt6Core.a				libQt6Network.a				libQt6Sql.a				metatypes
libQt6Core.prl				libQt6Network.prl			libQt6Sql.prl				objects-Release
libQt6DeviceDiscoverySupport.a		libQt6OpenGL.a				libQt6Test.a
libQt6DeviceDiscoverySupport.prl	libQt6OpenGL.prl			libQt6Test.prl
libQt6FbSupport.a			libQt6OpenGLWidgets.a			libQt6Widgets.a

And ~/.conan/data/qt/6.2.1///package/ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/lib/  Contains : ...				libQt6FbSupport.prl			libQt6OpenGLWidgets.prl			libQt6Widgets.prl
libQt6Concurrent.a			libQt6Gui.a				libQt6PrintSupport.a			libQt6Xml.a
libQt6Concurrent.prl			libQt6Gui.prl				libQt6PrintSupport.prl			libQt6Xml.prl
libQt6Core.a				libQt6Network.a				libQt6Sql.a				metatypes
libQt6Core.prl				libQt6Network.prl			libQt6Sql.prl				objects-Release
libQt6DeviceDiscoverySupport.a		libQt6OpenGL.a				libQt6Test.a
libQt6DeviceDiscoverySupport.prl	libQt6OpenGL.prl			libQt6Test.prl
libQt6FbSupport.a			libQt6OpenGLWidgets.a			libQt6Widgets.a
-----------------------------

... Nothing that looks like : libXCocoaIntegrationPlugin !

**Comment by dfleury2** [comment]
Can you list only the all files with .a extension (the static libs) ?
None of them has 'integration' in its name ?

How did you build this package ? by changing the version of your profile or recompiling everything locally with the default profile ?
For the first case, I will check if the cocoa integration is somewhere, for the second case may be an option must be added to build the cocoa integration plugin (or any other integration plugin to be load when using static library)

**Comment by tom1lee** [comment]
> None of them has 'integration' in its name ?

It seems not.

> 
> How did you build this package ? by changing the version of your profile or recompiling everything locally with the default profile ? For the first case, I will check if the cocoa integration is somewhere, for the second case may be an option must be added to build the cocoa integration plugin (or any other integration plugin to be load when using static library)

All packages have been build automatically.
This is the solution I found to validate conan install in the build dir correctly.
With the command:

`conan install --build=missing ..`

https://github.com/conan-io/conan/issues/10257

**Comment by dfleury2** [comment]
Can you try using the pre-built package on the conan center ?
(by updateing the version to 12 instead of 13), and see if a file that seems like 'cocoa inegration' is there or not ?
I will need to check the conanfile.py (the recipe) to see if something is need on our side

**Comment by dfleury2** [comment]
If I used this profile : 
[settings]
arch=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos

with the compiler.version set to 12.0 (instead of 13.0).
Conan download the package without any compilation.

Looking into the data directory, I have this files:
```
dfleury@pc-mno-05:~/.conan/data/qt/6.2.1/_/_$ find . -name "*Cocoa*"
./package/ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/res/archdatadir/plugins/platforms/objects-Release/QCocoaIntegrationPlugin_init
./package/ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/res/archdatadir/plugins/platforms/objects-Release/QCocoaIntegrationPlugin_init/QCocoaIntegrationPlugin_init.cpp.o
./package/ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/lib/objects-Release/QCocoaIntegrationPlugin_resources_1
```
Can you check you have the same files when compiling for the sources ?

I will disabled all useless applications in the CMakeLists.txt by default to reduce the number of fix to dofor this link error.

**Comment by tom1lee** [comment]
settings]
os=Macos
os_build=Macos
arch=x86_64
arch_build=x86_64
compiler=apple-clang
compiler.version=12.0
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]

...Here what i get with the same search:

`jeanjean@Mini-de-jean ~ % cd ~/.conan/data/qt/6.2.1/_/_/package
jeanjean@Mini-de-jean package % find . -name "*Cocoa*"               
./ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/res/archdatadir/plugins/platforms/objects-Release/QCocoaIntegrationPlugin_init
./ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/res/archdatadir/plugins/platforms/objects-Release/QCocoaIntegrationPlugin_init/QCocoaIntegrationPlugin_init.cpp.o
./ad0a97e4bdbb8ad784efbce1b0c84f840bb91425/lib/objects-Release/QCocoaIntegrationPlugin_resources_1
./9c39a041ef08c69eb3a82026999134a5b7aecf3b/res/archdatadir/plugins/platforms/objects-Release/QCocoaIntegrationPlugin_init
./9c39a041ef08c69eb3a82026999134a5b7aecf3b/res/archdatadir/plugins/platforms/objects-Release/QCocoaIntegrationPlugin_init/QCocoaIntegrationPlugin_init.cpp.o
./9c39a041ef08c69eb3a82026999134a5b7aecf3b/lib/objects-Release/QCocoaIntegrationPlugin_resources_1`

**Comment by dfleury2** [comment]
I have made a small step on Catalina. Using the CocoaIntegration plugin I have some _CV <something> missing.
It's like the package is missing some dependency to link. I will made some test on Monterey.
The more I use mac the more I hate it... So I will force myself ;)

**Comment by tom1lee** [comment]
> ... The more I use mac the more I hate it... So I will force myself ;)

Totally agree ! Apple has become a big pile of mud !

**Comment by tom1lee** [comment]
> I have made a small step on Catalina. Using the CocoaIntegration plugin I have some _CV missing. It's like the package is missing some dependency to link. I will made some test on Monterey. ...

Warning, I think macos 12.1 monterey is a trap !
I plan to reinstall everything under big sur !

**Comment by dfleury2** [comment]
Do, it seems to be ok now.
For the link issue, I have used some part of this page : 
https://jstookey.com/building-sdl2-projects-for-ios-with-xcode-11/

**Comment by tom1lee** [comment]
Cool ! Now build succeeded with Xcode and command line ! Many thanks !
