### ISSUE TITLE
MEMORY1.RC0 not reflecting state of looper

### ISSUE THREAD

**Issue by danmalks** [dfleury2/boss-rc500-editor#10]
Hi David,
Thanks for creating this app.

I haven't tried it yet, but really appreciate your efforts.

While attempting to understand how the RC-500 is saving state, I was having a look at the MEMORY1.RC0 (and related) files on the looper (using a Mac) and noticing that certain info that is saved on the looper doesn't seem to match what is in the MEMORY1.RC0 file...any idea why?

Wondering specifically about the "Assign" midi info.
When I update the Assign info for a specific memory in the RC-500 using the looper physical controls, then I look at the MEMORY1.RC0 file, I do not see those updates reflected in the file afterwards (but I do see them on the looper display).

Wondering if you have any insight into what you learned about this and how it saves its state. 

Thanks very much!
Dan

**Comment by dfleury2** [comment]
Hi,
it seems that the looper use the two files MEMORY1.RC0 and MEMORY2.RC0 as backup/restore in case of issue during a save.
I have not figure out how it works exactly, but the app will write both files.

To find the changes, you should look into both MEMORY1.RC0 and MEMORY2.RC0
The changes may be visible in one of these files.

ASSIGN are the hardest part to deal and I still have an issue in certain cases, and do not know how Boss deals with some inconsistent cases.

**Comment by danmalks** [comment]
Thanks for the info. 
I have checked both files and cannot find the "Assign" values in either file that shows what I've set on the looper.
I see that you do get/set assign in your app...does that actually work? 

Also, are you able to share a compiled version of your app for Mac, the link online isn't avail...thanks!

Dan

ps: If you don't mind continuing this via email, please email me at danmalks@gmail.com, I'd like to share some of my findings and I hope that will also help you diagnose issues in your application, which I'm happy to test for you, as well...thanks again

**Comment by dfleury2** [comment]
Oh yes, I have not made any announcement on this application (I am surprise that you find it).  It still in experimentation mode (even if it works pretty fine)
Here a page with a little documentation:
[http://simplecpp.free.fr/boss-rc500/](url)
and the download section
[http://simplecpp.free.fr/boss-rc500/downloads/](url)
the latest is 0.0.5

The MacOS is the version I am not sure how it will work for a MacOs user since I have never used a MacOs in my life ;)

**Comment by danmalks** [comment]
Thanks. I'll have a look.

Can you do me a favor.
Tell me if you are able to see any info change in MEMORY1.RC0 or MEMORY2.RC0 if you go into memory 10 on your looper (or any memory) and update:
Assign 1 to CC#1 and a target like Mem Inc
Assign 2 to CC#2 and a target like Mem dec
Assign 3 to CC#3 and a target like All Start
Assign 4 to CC#4 and a target like Trk Select

When I update the above on the looper I am not seeing these updates in either of these files...can you let me know what you see on your end?

Thanks!
Dan

**Comment by danmalks** [comment]
I am trying your app on Win10 64 bit and was able to update the assign values (using the app) so that the values did seem to update correctly on the pedal (nice work!)...yet when after that I go and look at the underlying MEMORY1.RC0 and MEMORY2.RC0  files by loading them into an editor, I do *not* see the updated values reflected there in those files...any idea why we would see values persisted on the rc-500, but yet not see those values in those files?

Thanks!

**Comment by dfleury2** [comment]
![image](https://user-images.githubusercontent.com/4805384/155897213-29c7ce5f-f8bd-45ab-8ab0-6473b027ee76.png)
This is where the changes are visible if I update memory 10

**Comment by danmalks** [comment]
That makes sense.
But for some reason even after changing the looper settings and seeing those changes persisted in the looper, I do not see these updates showing up on the MEMORYx.RC0 files on the looper. Wonder if the looper can persist/get these values from anywhere else.

Are you doing anything to force an update of those files after modifying them...not sure what more I can do except disconnect the looper, turn it off and then on again. 

Also, how did you figure out the values to write from the app for Source and Target in <Assign>, are those documented somewhere?

Thanks again.

Also, let me know if there's anything you'd like me to test in the app, happy to help if you need anything. 

Dan

**Comment by dfleury2** [comment]
If you made the changes on the looper, you must write them in the memory (EXIT + ENTER button).
this should write the changes in one of the files (either MEMORY1.RC0 or MEMORY2.RC0)

if you change some values with the application, you open the files directly on the USB connected drive or copy the files saved in the USB connected disc of the Boss.
After that, you need, to disconnect the looper by disconnect the storage mode.

For the tests, you just have to use the app, and if you see a unexpected value on the looper (one that is different from the app), you can open a ticket ;)

The only bugs known are the max value for assign and some rythm not available when beat pattern is complexe (not 4/4)

**Comment by danmalks** [comment]
Yes, this is exactly how I've been doing it, but still seeing the files not
updating...odd, not sure why.
Anyway, I'll file a bug if I see anything, thanks!

Also, can you tell me how you would do the following:
What if I want to set all the Assign values for every memory to the same
"default" values to start?
ie: Assign1 and Assign8 would be assigned certain settings in one memory
using the app and those exact same settings would be copied to each and
every memory.

Any way to do this easily via your application vs setting each memory
individually?

Thanks,
Dan

**Comment by dfleury2** [comment]
On the rigth of the copy button there is an angle bracket
![image](https://user-images.githubusercontent.com/4805384/155900065-496a9bab-3b82-43f6-9c27-024ef6a8e440.png)
You can select which part you want to copy to the memory range selected.
![image](https://user-images.githubusercontent.com/4805384/155900082-494f2d88-1a1b-445e-9f11-fa62558efd7c.png)
It seems that I forget to add the ASSIGN section.

**Comment by danmalks** [comment]
You are right, adding "ASSIGN" to this dialog would cover this use case for sure.
I'm sure you are busy, so don't want to presume any timeline on your adding this feature, but just let me know if you want me to open another issue or if this will suffice as a reminder. 

Thanks very much, really appreciate the open communication and thanks for working on such an extremely useful application.

Dan

**Comment by dfleury2** [comment]
I have just published a 0.0.6 version with the assign available.
Thanks

**Comment by danmalks** [comment]
Thanks! Really appreciate it!
I just tested it a bit...should I report feedback here?

If so, here goes:
I was on Memory 13 (for no real reason) and wanted to copy the ASSIGN values from Memory 10 to Memory slots 1-9.
Wasn't clear how to do this using the current interface, so figured I'd start by trying to see if it worked to copy the ASSIGN values from Memory 10 to Memory 9, so I selected "from 10 to 9" in the UI. 

Here is what the app prompted:
![bossAppIssue-1](https://user-images.githubusercontent.com/6364118/155903144-66a4405b-40b1-4b99-a10a-95d5cd7076a8.PNG)

Anyway, let me know how you intend for things to work and I can approach it that way for now and am also happy to provide some feedback on that UI approach (once I understand how you'd like to approach this). 

Thanks!
Dan

**Comment by danmalks** [comment]
Okay, I revisited this and realize that I was confused by the UI and was indeed able to accomplish what I wanted as I noticed there is a separate From and To in the modal dialog box. 

Thanks

**Comment by dfleury2** [comment]
I will improve that and copy the from/to from the main screen to to ones in the dialog box.
I will duplicate the control about "FROM" that must be less or equa than the "TO"
Here it should be FROM 9 and TO 10

**Comment by danmalks** [comment]
Hi,
Is batch copying of rhythm state (ie: setting memory 80 to 99 to have State: READY vs OFF) working?
I tried it and didn't see the results I expected, but wondering if it was user error.

Thanks

**Comment by dfleury2** [comment]
Hi,
it should yes.
![image](https://user-images.githubusercontent.com/4805384/157237919-3d067ccd-ce02-457b-8f8d-bdeb84d25e1e.png)

The State value should change to 0 to 1

**Comment by chtenb** [comment]
> it seems that the looper use the two files MEMORY1.RC0 and MEMORY2.RC0 as backup/restore in case of issue during a save.
I have not figure out how it works exactly, but the app will write both files.

From what I've deduced the first byte of the end tag determines the "version" number. The file with with the highest version byte wins and will be used by the rc500 as the newest file. The version number wraps around 127 and can be NULL (so the file is not always valid utf-8 :)

I haven't looked in the source code and I don't know which of the two files this app will use, but it should be the newest one :)
