### ISSUE TITLE
Error received when trying to write settings

### ISSUE THREAD

**Issue by allenhuish** [dfleury2/boss-rc500-editor#11]
Thank you for a fantastic project.

I am trying to save to my RC-500 and I receive the following error message:

[inja.exception.file_error] failed accessing file at './resources/templates/MEMORY.txt'

I am on Mac OS X Monterey. I have a feeling that the problem is permissions for the app to access the directory - I will try to have a look at that.

I have tried running the app both from the disk image and from the 'Applications' folder.

I cannot write anything to the device because of this.

UPDATE:
I have given the app full disk access through the control panel and I am still receiving the error so this does not appear to be a permission/security issue.

**Comment by allenhuish** [comment]
This is the information from the startup in the terminal window:

Resource Path [/Applications/BOSS/RC/resources]
Loading font file [/Applications/BOSS/RC/resources/fonts/D-DINCondensed.ttf]
[D-DIN Condensed] font family loaded
Loading theme file [/Applications/BOSS/RC/resources/themes/Default.css]
Loading theme file [/Applications/BOSS/RC/resources/themes/Empty.css]
Add theme file [/Applications/BOSS/RC/resources/themes/Empty.css]
Loading theme file [/Applications/BOSS/RC/resources/themes/GT1000.css]
Add theme file [/Applications/BOSS/RC/resources/themes/GT1000.css]
Loading theme file [/Applications/BOSS/RC/resources/themes/gt1000.png]
bad file: /Applications/BOSS/RC/resources/configuration.yaml
Memory: 1, Track: 1, Measure: 1
Memory: 1, Track: 2, Measure: 1
Beat signature: 4/4
qt.qpa.fonts: Populating font family aliases took 242 ms. Replace uses of missing font family "D-DIN Condensed" with one that exists to avoid this cost. 
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by dfleury2** [comment]
Hi,
the app is looking for a file named 'MEMORY.TXT' which is not found there : /Applications/BOSS/RC/resources/templates

It seems that the app is installed here : /Applications/BOSS
it will be used as root dir for the resources
I will check if I can fix the package but I have no Monterey available.

**Comment by allenhuish** [comment]
Thanks for your reply.

The file is in the correct directory, but it is called 'MEMORY.txt' not 'MEMORY.TXT'

**Comment by dfleury2** [comment]
Ok my bad.
does it work when you rename the file ?
I will make a patch later

**Comment by allenhuish** [comment]
I will test it.

**Comment by dfleury2** [comment]
I have made a fix, that works locally for me (under BigSur)
can you try the latest dmg package ? (0.0.7)

http://simplecpp.free.fr/boss-rc500/downloads/Boss-Rc500-Editor-0.0.7-Darwin.dmg

**Comment by allenhuish** [comment]
I have just tested it (only once) and the error message is gone.

I edited the name of a memory and then wrote it to the device and it was recognised.

Thank you so much!
