### ISSUE TITLE
Behaviour of copy memory button

### ISSUE THREAD

**Issue by allenhuish** [dfleury2/boss-rc500-editor#12]
Hi there,

How is the copy memory button supposed to behave?

For example, if I select '1' and '10' in the copy dropdown lists, when I press the button it says 'Do you want to copy memory slot 1 into slots from 1 to 10?'

This seems to copy everything from memory to slot 1 into EVERY memory from 1 to 10 (2,3,4,5,6,7,8,9,10 now have the settings from slot 1).

This is very good, because it allows assigns to be set up once and then put into all of the slots.

BUT how would I take settings from memory1 and just put them into one slot e.g. from memory1 to memory23?

Is that possible?

2nd question:

The detailed copy dialog box that allows selection of categories to copy between memories: is this only active when it is shown? or does it persist?

Thank you

**Comment by dfleury2** [comment]
Hi,

> Hi there,
> 
> How is the copy memory button supposed to behave?
> 
> For example, if I select '1' and '10' in the copy dropdown lists, when I press the button
> it says 'Do you want to copy memory slot 1 into slots from 1 to 10?'
> 
> This seems to copy everything from memory to slot 1 into EVERY memory from 1
> to 10 (2,3,4,5,6,7,8,9,10 now have the settings from slot 1).
> 
> This is very good, because it allows assigns to be set up once and then put into all of the slots.


Correct this is the expected behavor, the memory 1 will be copied to all memories from <start> to <finish> included.

> 
> BUT how would I take settings from memory1 and just put them into one slot e.g. from memory1 to memory23?
> 
> Is that possible?

Yes, it should, if you set from 23 to 23. It should only copy the memory selected to the slot 23

> 
> 2nd question:
> 
> The detailed copy dialog box that allows selection of categories to copy between memories: 
> is this only active when it is shown? or does it persist?

No, it's only active when visible, else it will copy all parts.
Each time you want to select only some parts you need to click on the '>' button (advanced copy mode)

> 
> Thank you

You are welcome.

**Comment by allenhuish** [comment]
Thank you for your help. It's now much clearer that it is copying what is shown on screen into the memory slot. I was thinking that it was copying from the current memory slot.

If I get a chance I may do a youtube video demonstrating the software.

Would that be okay with you?

**Comment by dfleury2** [comment]
I was thinking about it, but my english is quite 'frenchy' 
I will first try to clarify the doc present here: [https://dfleury2.github.io/boss-rc500-editor/#/](https://dfleury2.github.io/boss-rc500-editor/#/)
or here [http://simplecpp.free.fr/boss-rc500/#/](http://simplecpp.free.fr/boss-rc500/#/)

**Comment by allenhuish** [comment]
No, I was suggesting that **I** would make a video

**Comment by dfleury2** [comment]
Oh yes, it will be great.
So I can see how it is used, and improve it.
