### ISSUE TITLE
Colorblind person: possible to change colors of REC/PLAY/DUB?

### ISSUE THREAD

**Issue by MarByteBeep** [dfleury2/boss-rc500-editor#18]
Do you happen to know if through a configuration it would be possible to change the factory colors of PLAY (green), OVERDUB (yellow) and RECORD (red)? For colorblind people, the distinction between green and yellow is just impossible. Unfortunately, BOSS doesn't seem to offer it in the settings, so hopefully you might know a solution?

**Comment by dfleury2** [comment]
Hi,
I do not think you can change the color of the LED embedded inside the looper itself.
At least, I have not seen anything related to these colors in the XML file.

**Comment by MarByteBeep** [comment]
Thanks! I've reached out to boss as well. Otherwise I might take a stab at reverse engineering the firmware 😊
