### ISSUE TITLE
App doesn't seem to do much on FW v1.10

### ISSUE THREAD

**Issue by MarByteBeep** [dfleury2/boss-rc500-editor#19]
I tried running the app on my new RC 500 with firmware version v1.10 (released dec 2023). But no matter what I do in the app, nothing is updated on the device itself. Any thoughts?

**Comment by dfleury2** [comment]
Hi,
I have not tried this update.
Do you use the app on Mac, Windows or Linux ?
Do you have access to the XML files while the RC-500 is connected to your PC ?

**Comment by MarByteBeep** [comment]
I'll go test it. What do you mean with access to the XML files? Where should they be located?

**Comment by dfleury2** [comment]
When connected to a PC, the Boss RC-500 is seen as a USB Drive. Depending on your OS, it can be E:\ or /media/...
but the files that manage the configuration is accessible. The app will try to load these files and rewritte them.
They are loaded when you made a File > Open and choose a directory.
At this time, I have not found how Boss so with their own tools to automatically connect the boss is this USB drive mode. So you need first to go the RC-500 to go on USB drive mode.

https://youtu.be/wfjOkf3fP58?t=33

should help

I think someone has made a video on the app on facebook on how to connect it.

https://www.youtube.com/watch?v=T55ZMf9tQ0E&t=4s

**Comment by MarByteBeep** [comment]
Thanks a lot for this! I'll give it a try and close this for now.
