### ISSUE TITLE
Version windows du 02/01/2022

### ISSUE THREAD

**Issue by Chatlut** [dfleury2/boss-rc500-editor#2]
Bonjour.
Après test de la version windows du 02/01/2022 que tom1gozzi à poster sur son compte OneDrive.
[https://onedrive.live.com/?authkey=%21ALlZ4OaYjiIlLzs&id=DA3414B8F6017596%21156036&cid=DA3414B8F6017596](url)

Voici les axes d'améliorations :

1. Il manque les fonction "réduire" et "agrandir" en haut à droite à coté de "fermer".
2. L'affichage de la version serai également un plus.
3. J'ai fais une version PDF traduite en français si tu veux pour les fenêtre d'aide contextuelles. Je te dépose le PDF en pièce jointe.
[RC-500 Parametres fr.pdf](https://github.com/dfleury2/boss-rc500-editor/files/7826763/RC-500.Parametres.fr.pdf)
4. L'aide contextuelle **TRACK 2 > Loop Sync** ne s'affiche qu'une demi seconde puis disparait. Ca s'affiche bien pour TRACK 1.
5. Même problème pour tous les targets de **MENU > ASSIGN... > TARGET** 
6. L'aide contextuelle de **CONTROL > Pedal 1** à **CONTROL > Control 2** à une police d'affichage floue.
7. Il manque l'aide contextuelle dans ** SYSTEM...**

Merci pour ce logiciel génial.

**Comment by dfleury2** [comment]
1/ C'est corrigé. La fenêtre principale n'est plus une boite de dialogue.
2/ Je ferai une boite "About" quand j'aurais stabilisé la version sous MacOs, pour le moment, je pourrais au moins mettre la date/heure de compilation pour avoir une indication de la version utilisée.
3/ Joli travail.
Ca fait parti des question qu'on peut se poser. Est-ce que Boss autoriserait de distribuer la doc même traduite ?

4/, 5/ et 6/ Malheureusement, je n'ai pas le main sur l'affichage des tooltips. J'ai fait une copie d'écran de la doc en image.
Quand l'image est trop grande pour l'écran, ça peut arriver que le tooltip disparaisse juste après s'être affiché.
Il faut parfois déplacé l'écran principal pour que le tooltip reste.
Pareil pour le flou, comme il y avait trop de texte, l'image était trop grande, j'ai donc du réduire l'image, ce qui induit un flou (gaussien ici).
Une autre solution serait de prendre les images et les saisir un mode html dans un fichier externe qui pourrait être relu.
Pour être valable il faudrait voir si Qt6 gère mieux les textes longs dans les tooltips (avec des ascenceurs par exemple).
Il faut que je fasse un exemple, mais c'est clairement quelque chose qui pourra être fait par quelqu'un d'autre. Ca prend beaucoup de temps tout seul (bonjour le temps pris pour faire les copier/coller du pdf en png).

7/ J'en ai eu un peu marre à vrai dire, c'était long...

**Comment by Chatlut** [comment]
Je peux faire les copier/coller du pdf en png pour la partie SYSTEM si tu veux et je te les dépose sur ce fil de discussion.

**Comment by dfleury2** [comment]
Je vais essayer de faire plus simple avec des morceaux en html directement.
Je vais voir si Qt6 gère mieux ça quand c'est long. On pourra toujours intégrer des images comme pour la doc.
Après, je ne sais pas trop encore comment gérer la partie anglais/français. Peut être une option dans le menu.

**Comment by Chatlut** [comment]
On peut imaginer ajouter des choix à faire dans les préférences:

1. Choix de la langue
2. Choix d'afficher les tooltips ou pas.

**Comment by dfleury2** [comment]
Voilà, ce que ça peut donner avec juste du html.
L'idée serait de mettre uniquement le texte (par langue) dans un fichier tooltip, pour être rechargé à la volée.
En mettant le plus de chose possible paramétrable (avec une valeur par défaut cohérente avec l'image du tooltip aujourd'hui)

![image](https://user-images.githubusercontent.com/4805384/148742285-20b20503-0fd9-4042-a6b3-677577c2c98b.png)

Je ne sais pas si tu connais le HTML mais dans le code ça donne ça:
Un utilisateur n'aurait à saisir que le contenu des cellules (ici : Pan , L50-CENTER-R50, et "Specifies the stereo...".
Tu vois l'idée

```
<html>
<table width="700" style="border-collapse: collapse; font-size:14px;">
    <thead>
    <tr>
        <th width="100" style="background-color:#a5c5af;border-bottom: 3px double grey;border-right: 1px solid grey;">Parameter</th>
        <th width="200" style="background-color:#a5c5af;border-bottom: 3px double grey;border-right: 1px solid grey;">Value (Bold: default)</th>
        <th style="background-color:#a5c5af;border-bottom: 3px double grey;border-right: 1px solid grey;">Explanation</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th style="background-color:#cdd8ea;border-right: 1px solid grey;">PAN</th>
        <td style="border-right: 1px solid grey;text-align:center;">L50-<span style="font-weight:bold; color:#00548f;">CENTER</span>-R50</td>
        <td style="border-right: 1px solid grey;">Specifies the stereo position (pan) of the track</td>
    </tr>
    </tbody>
</table>
</html>
```

**Comment by Chatlut** [comment]
Oui ça semble très bien.
Je ne connais pas plus que ça le language de programmation.
Que se soit HTML ou autre mais c'est peut être pas si compliqué que ca avec un éditeur pour débutant...
Ou pas ... je ne me rend pas compte.
Mais je suis toujours motivé pour rendre service.

**Comment by Chatlut** [comment]
Je peu utiliser notepad++
Ou bien visuzl studio code qui semble compatible avec github

**Comment by dfleury2** [comment]
Voici un exemple pour le TRACK.REVERSE

![image](https://user-images.githubusercontent.com/4805384/148770934-e6eeb684-e7ab-400a-b22f-f124a17d2b6d.png)

Le fichier utilisé pour générer le tooltip ressemble à :
```
Parameter: REVERSE

Explanation:
  Specifies conventional playback (OFF) or reverse playback (ON).
  <br>(*) When REVERSE is set to “ON,” you won’t be able to switch to overdubbing after a recording
  has been completed.

Details:
  - Value: OFF
    Default: True
    Detail:
      Conventional playback.

  - Value: ON
    Detail:
      Reverse playback.
```

Ca peut être édité simplement avec un éditeur de texte tout simple genre Notepad++ (notepad c'est un peu rude).
C'est un fichier au format yaml, donc l'indentation est importante.

Pour le moment, je suis encore en phase de  test pour voir si on peut tout faire comme ça. Parfois, il semble que je sois obligé d'inclure quand même une image. Je vais voir si j'améliore le truc pour les valeurs simple de type OFF/ON comme la doc Boss.

La taille de la police peut être modifiée dans les fichiers Themes > Default
QToolTip { font-size:... }

**Comment by dfleury2** [comment]
C'est terminé... enfin la partie moteur pour la génération des tooltips.
Il y a maintenant un menu préférences pour choisir la langue des tooltips.

dans le répertoire ./resources/tooltips/

Les fichiers track_start.yaml et track_reverse.yaml sont des exemples de mise en place de traduction en francais (fr).

L'idée est d'ajouter ".fr" après soit Explanation, soit Detail pour avoir le texte disponible dans la langue souhaitée.
Tous les autres fichiers sont des exemples pour faire tous les tooltips possibles, et peuvent servir d'exemple.

Les tooltips trop long sont maintenant affichés dans une boite de dialogue dédiée, accessible par un boutont "?"
