### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by tmessink** [dfleury2/boss-rc500-editor#21]
Hi,
First off, Awesome job on the RC500 Editor!!
I have a few questions:
1)What Parameters are saved when saving a preset?
2) Is a preset the same as a full memory location?
3) I'm thinking that I can build a memory location in the RC500, load it into the editor and save it as a preset under presets. Is this correct?
4) This is actually an RC500 question:
I'm trying to build a midi controlled ALL STOP button.  I'm using 3 assigns, using T1 STOP, T2 STOP and Rhythm STOP and connecting them all to Midi CC#24.  Some respond when I hit the button, some don't.
Do you know how many assigns I can connect to 1 Midi CC#?
Thank you so much!

**Comment by dfleury2** [comment]
Hi,
thanks.

1/ All parameters of a memory slot are saved (assign included)
2/ Not sure to understand but regarding my first answer I wuld say yes.
3/ Correct. For the preset to appear in the menu File > Load preset >...  You need to restart the app.
Another way is to set some parameter in a specific memory slot, then copy it to different slots using the copy button.

4/ Sorry I do not know, I have mostly used the RC500 to write the app, and not actually using it ;)

**Comment by tmessink** [comment]
Thank you so much for your quick response!
This is a great asset to the looper!
Strong work!!
