### ISSUE TITLE
Pas fonctionnel avec Windows 11

### ISSUE THREAD

**Issue by vidalv** [dfleury2/boss-rc500-editor#22]
Bonjour, je viens de télécharger les deux versions, Boss-Rc500-Editor-0.0.9-win64.zip et Boss-Rc500-Editor-0.0.10-win64.zip, aucune des 2 ne fonctionnent sous windows 11, il y a une astuce ? Merci.

**Comment by dfleury2** [comment]
Bonjour,
pas d'astuce, juste peut être cliquer sur "informations complémentaires" puis "exécuter quand même".

**Comment by vidalv** [comment]
Bonjour et merci, pas d"informations complémentaires", une precision, la RC-500 n'est pas connecté au démarrage du programme, il existe bien un fichier MEMORY_DEFAULT.RC0 ainsi que SYSTEM_DEFAULT.RC0 dans le repertoire  Boss-Rc500-Editor-0.0.10-win64\resources\templates. Lors du lancement une fenêtre furtive s'ouvre et se referme immédiatement sans que je puise voir quelque chose. Merci.

**Comment by dfleury2** [comment]
Il faudrait lancer le programme dans une console (raccourci fenetre + R, puis dans Ouvrir, taper cmd),
et voir le message d'erreur qui s'affiche dans la console.

Normalement, en décompressant le fichier .zip (tous les fichiers), cela doit fonctionner directement. Etrange.

**Comment by vidalv** [comment]
Merci, l’exécution dans un command prompt donne : 
D:\Boss\Boss-Rc500-Editor-0.0.10-win64>BossRc500.exe
Resource Path [D:/T├®l├®chargements/Boss/Boss-Rc500-Editor-0.0.10-win64/resources]
Loading font file [D:/T├®l├®chargements/Boss/Boss-Rc500-Editor-0.0.10-win64/resources/fonts/D-DINCondensed.ttf]
[D-DIN Condensed] font family loaded
No root tag database found

Si ça dits qq-chose ?
Merci.

**Comment by dfleury2** [comment]
Oui, c'est que le fichier XML lu n'est pas correct.
Il devrait trouver une balise <database>
dans le répertoire ./resources/templates/  les deux fichiers RC0 doivent être exactement
![image](https://github.com/user-attachments/assets/171e237c-5315-4809-ad62-834d4e4836d4)

commencé comme ça :

![image](https://github.com/user-attachments/assets/a4617743-55ee-4488-b59f-f2c3b375d2d4)

**Comment by vidalv** [comment]
Merci, le répertoire "templates" existe bien, il y a 4 fichiers dedans, : 
![Templates](https://github.com/user-attachments/assets/be9cb32a-c064-45bc-94c2-4d84ca8b154b)
Le fichier MEMORY_DEFAULT.RC0 semble correcte : 
![Memory](https://github.com/user-attachments/assets/02e5d0fc-1d1d-4513-9ed2-d11b43179394)
😵

**Comment by dfleury2** [comment]
C'est bizarre.
L'erreur correspond à une erreur de lecture d'un de ces fichiers.
Normalement, rien de spécifique à à faire Windows11 juste extraire le .zip et lancer le binaire.

**Comment by dfleury2** [comment]
Oui, j'utilise et je le teste sous Windows 11 pro et Ubuntu.
Aucune idée pourquoi ça ne fonctionne pas pour vous.
Est-ce qu'il y aurait des droits restreints quelque part ?

**Comment by vidalv** [comment]
Bonjour et merci, non je suis en administrateur sur cette machine, l’exécution de la résolution de problème ne donne rien non plus.
![Propriétés](https://github.com/user-attachments/assets/b62e4ff0-4efc-4bb3-9585-3f2a3f09789c)
Il faut que je trouve une autre machine avec Windows 11 pour vérifier si cela viens de mon système ...

**Comment by vidalv** [comment]
Bonsoir, de retour sur le sujet. Alors, j'ai fait plusieurs tests. 1) Actuellement, lorsque je lance le programme il est sur mon deuxième disque physique D:\ j'ai l'erreur. 2) J'ai fait une copie sur une clef USB, si je lance depuis la clef USB le programme se lance normalement. 3) J'ai copié le programme sur mon disque principale C:\ la aussi ça fonctionne. ça résous mon problème mais c'est assez bizarre comme comportement non ?

**Comment by dfleury2** [comment]
Bonsoir,
c'est étonnant. Je vais voir si j'ai le même problème sur mes autres disques.

**Comment by dfleury2** [comment]
Je n'ai pas réussi à reproduire sur mes 3 disques C, D et E fonctionnent correctement. Aucune idée d'où peut venir le problème remonté.

**Comment by vidalv** [comment]
Merci David, ça fait probablement, parti des mystères de Windows .... Bon, ceci étant ça fonctionne sur C:\ sur ma machine. Encore merci et bravo !
