### ISSUE TITLE
File Preferences

### ISSUE THREAD

**Issue by vidalv** [dfleury2/boss-rc500-editor#23]
Bonjour David, est-ce que la fonctionnalité du menu File -> Preferences est active ? 
Si oui, comment ça fonctionne ? 
Merci.
![Prefs-French](https://github.com/user-attachments/assets/6772d9e3-ae3a-4eac-8338-3227826153a1)

**Comment by dfleury2** [comment]
Bonsoir,
cela n'est valable que pour les tooltips.
dans le répertoire resources/tooltips, il y a le fichier track_start.yaml  qui montre comment cela fonctionne.
Il suffit d'ajouter un bloc "Explanation.<la langue voulue>" et ça va changer le tooltip selon la langue choisie.
Par défaut ça utilise la section Explanation ou Detail sans le suffixe.

Dans le fichier configuration.yaml, il est possible d'ajouter d'autre langue.

Quelque part sur le forum de Guitar plug'n'play quelqu'un avait traduit la notice en français.

**Comment by vidalv** [comment]
Bonjour David, comment est-il possible d'accéder au menu CONTROL ?
![Ctrl](https://github.com/user-attachments/assets/e06d3504-1476-490f-95a8-3860e37aacbb)
L'ensemble des options restent grisées, il y a une condition ?
Merci.
