### ISSUE TITLE
Bouton pour désactiver, mettre en veille le RHYTHM

### ISSUE THREAD

**Issue by Chatlut** [dfleury2/boss-rc500-editor#3]
Bonjour. 
Un petit message pour penser à ajouter le bouton pour désactiver, mettre en veille le RHYTHM.
Merci.

**Comment by dfleury2** [comment]
Bonjour,
j'ai regardé ça en détail. Donc le looper ne sauve pas l'état "ON".
Je vais ajouté, un paramètre pour OFF (lumière éteinte) et READY (lumière cllignotante) uniquement.

**Comment by dfleury2** [comment]
Et voilà: 
![image](https://user-images.githubusercontent.com/4805384/148734798-bd9c8edf-c4bb-4822-bd65-8d218b89fc55.png)
![image](https://user-images.githubusercontent.com/4805384/148734824-69eff856-57c4-487c-9737-c3579840cf7a.png)

**Comment by Chatlut** [comment]
Oui. 
"ON" ne peut pas fonctionner car ça démarre le rythme lorsque la boucle n'est pas lue.
Alors que "READY" démarre le rythme en même temps que la boucle démarre.
En tous cas merci.
Je test ça dès que j'ai accès à la version EXE mise à jour.
