### ISSUE TITLE
Fonction COPY

### ISSUE THREAD

**Issue by Chatlut** [dfleury2/boss-rc500-editor#7]
J'ai renommé toutes mes MEMORY avec la fonction EDIT.
J'ai ensuite utilisé la fonction COPY pour modifier certain paramètres.
Malheureusement le nom de la MEMORY utilisée pour la copie à également été copié.
![image](https://user-images.githubusercontent.com/97257356/149032247-b9638fdb-a951-4417-a08a-5f171a1fdf5d.png)

**Comment by dfleury2** [comment]
fix
