### ISSUE TITLE
Amélioration de la fonction COPY.

### ISSUE THREAD

**Issue by Chatlut** [dfleury2/boss-rc500-editor#8]
Bonsoir.
La fonction COPY est géniale. C'est surement la plus utile.
Elle pourrais peut être faire l'objet d'ajout d'options à cocher.
Exemple : 
Je veux copier toute ma configuration sauf ce qui concerne la partie des options de RHYTHM.
Ou bien copier uniquement ma configuration des options de PLAY.

En gros il faudrait pourvoir sélectionner ou désélectionner TRACK1, TRACK2, RHYTHM, RECORD, LOOP FX, CONTROLE lorsque on souhaite utiliser la fonction COPY.

Merci.

**Comment by dfleury2** [comment]
Bonjour,
oui, j'avais prévu ça comme usage.
Je mets de côté. C'est un peu long à faire à cause des cases à cocher. Si c'est par groupe c'est jouable.

**Comment by dfleury2** [comment]
Done

**Comment by Chatlut** [comment]
J'ai hâte de tester tout ça.
Merci
