### ISSUE TITLE
undo / redo

### ISSUE THREAD

**Issue by Chatlut** [dfleury2/boss-rc500-editor#9]
Bonjour.
Pensez vous qu'il soit possible d'ajouter une fonction ANNULER / REFAIRE ?
![image](https://user-images.githubusercontent.com/97257356/149360053-257c9271-4bbe-4024-baa4-d5c2d2b5431b.png)
Ca obligerai surement à avoir une gestion de fichiers temporaires en cache.
Cordialement.

**Comment by dfleury2** [comment]
Comme je dis à mes responsables, si je réponds non, c'est que je suis un incapable ;)
Donc oui, c'est possible. Ca demande juste pas mal de temps pour le mettre en place et que ça fonctionne bien
(comme la gestion du statut modifié/original des champs ou même du fichier complet).
A garder sous le coude.

**Comment by Chatlut** [comment]
Oui c'est une fonction qui serai pratique.
Mais qui n'est pas à traiter en priorité.
🥳

**Comment by dfleury2** [comment]
Done
version "provisoire". Seul l'écran Main est concerné, et certains champs (Beat) ont des effets de bord étrange. C'est lié à la gestion des index / valeur qui n'est pas top. Je changerais plus tard mais c'est lourd à faire.

Globalement, le undo/redo fonctionne, et le Show/Hide permet de voir tout ce qui est fait, et on peut sélectionner où on veut aller directement.

Attention lors des changements de mémoire.
